url                      : https://whitammer.github.io # the base hostname & protocol for your site e.g. "https://mmistakes.github.io"
repository               : "whitammer/whitammer.github.io"
logo                   : "images/portrait3.jpeg"
title                     : "Esmeralda S. Whitammer"